import '../models/recipe.dart';

const List<Recipe> mockRecipes = [
  Recipe(
    id: 'r1',
    name: 'Spaghetti Carbonara',
    imageUrl: 'image/pexels-nano-erdozain-120534369-29039085.jpg',
    ingredients: ['Spaghetti (200g)', 'Trứng gà (2 quả)', 'Phô mai Pecorino (50g)', 'Thịt ba rọi xông khói (100g)', 'Tiêu đen'],
    steps: ['Luộc mì Spaghetti 8-10 phút.', 'Cắt thịt ba rọi thành hạt lựu, xào cho đến khi giòn.', 'Đánh tan trứng với phô mai bào nhỏ và tiêu.', 'Vớt mì đã luộc (giữ lại chút nước) cho vào chảo thịt. Tắt bếp.', 'Đổ hỗn hợp trứng phô mai vào, đảo nhanh tay. Hơi nóng của mì sẽ làm chín trứng.', 'Thêm chút nước luộc mì nếu quá khô. Thêm tiêu và thưởng thức.'],
    durationInMinutes: 20,
    category: RecipeCategory.food,
  ),
  Recipe(
    id: 'r2',
    name: 'Phở Bò Hà Nội',
    imageUrl: 'image/PhoBo.jpg',
    ingredients: ['Bánh phở (500g)', 'Thịt bò (thăn, nạm) (300g)', 'Xương ống bò (1kg)', 'Hành tây (1 củ)', 'Gừng (1 nhánh)', 'Thảo quả, hoa hồi, quế', 'Hành lá, ngò rí, chanh, ớt'],
    steps: ['Rửa sạch xương ống, chần qua nước sôi. Ninh xương với gừng, hành nướng và gia vị thảo mộc trong 4-6 giờ.', 'Lọc lấy nước dùng trong.', 'Thái mỏng thịt bò.', 'Trần bánh phở qua nước sôi.', 'Cho phở, thịt bò vào tô, chan nước dùng đang sôi.', 'Thêm hành lá, ngò rí và thưởng thức cùng chanh, ớt.'],
    durationInMinutes: 360,
    category: RecipeCategory.food,
  ),
  Recipe(
    id: 'r3',
    name: 'Bánh mì nướng Bơ Tỏi',
    imageUrl: 'image/BanhMiNuongBoToi.jpg',
    ingredients: ['Bánh mì baguette (1 ổ)', 'Bơ lạt (100g)', 'Tỏi (3 tép)', 'Ngò rí (1 nhúm)', 'Muối (1/4 muỗng cà phê)'],
    steps: ['Cắt bánh mì thành lát xéo dày 1.5cm.', 'Băm nhuyễn tỏi và ngò rí.', 'Để bơ mềm ở nhiệt độ phòng. Trộn bơ với tỏi, ngò rí và muối.', 'Phết hỗn hợp bơ tỏi lên đều hai mặt bánh mì.', 'Nướng ở 180°C trong 10-12 phút cho đến khi vàng giòn.'],
    durationInMinutes: 15,
    category: RecipeCategory.food,
  ),
  Recipe(
    id: 'r4',
    name: 'Bún Chả Hà Nội',
    imageUrl: 'image/BunCha.jpg',
    ingredients: ['Bún rối (1kg)', 'Thịt ba rọi (500g)', 'Thịt nạc vai (500g)', 'Su hào, cà rốt, đu đủ xanh', 'Nước mắm, đường, tỏi, ớt', 'Rau sống ăn kèm'],
    steps: ['Thịt ba rọi thái miếng. Thịt nạc vai băm nhuyễn làm chả viên. Ướp cả hai loại thịt với nước mắm, đường, hành tím.', 'Pha nước chấm: nước mắm, đường, giấm (hoặc chanh), tỏi, ớt theo tỉ lệ vừa ăn.', 'Làm dưa góp: thái mỏng su hào, cà rốt, đu đủ, ngâm giấm đường.', 'Nướng thịt và chả viên trên than hoa cho đến khi vàng thơm.', 'Cho chả, thịt nướng vào bát nước chấm nóng, thêm dưa góp.', 'Ăn kèm bún và rau sống.'],
    durationInMinutes: 60,
    category: RecipeCategory.food,
  ),
  Recipe(
    id: 'r5',
    name: 'Cánh gà rán ',
    imageUrl: 'image/CanhGaRan.jpg',
    ingredients: ['Cánh gà (1kg)', 'Bột chiên giòn (150g)', 'Trứng (1 quả)', 'Sữa tươi không đường (50ml)', 'Gia vị: tỏi bột, hành bột, ớt bột paprika, muối, tiêu'],
    steps: ['Rửa sạch cánh gà, để ráo. Ướp gà với muối, tiêu, tỏi bột, hành bột, ớt bột trong 30 phút.', 'Pha bột ướt: trộn trứng và sữa tươi.', 'Pha bột khô: trộn bột chiên giòn với chút muối và ớt bột.', 'Nhúng gà qua bột ướt, sau đó lăn đều qua bột khô.', 'Chiên ngập dầu ở lửa vừa (170°C) trong 10-12 phút cho đến khi gà chín vàng giòn.', 'Vớt ra để ráo dầu và thưởng thức.'],
    durationInMinutes: 45,
    category: RecipeCategory.food,
  ),
 
  Recipe(
    id: 'r7',
    name: 'Cơm rang Dương Châu',
    imageUrl: 'image/ComChienDuongChau.jpg',
    ingredients: ['Cơm trắng (để nguội) (2 bát)', 'Trứng gà (2 quả)', 'Lạp xưởng (1 cây)', 'Chả lụa (100g)', 'Đậu Hà Lan, cà rốt, bắp Mỹ (100g)', 'Tôm (100g)'],
    steps: ['Tất cả nguyên liệu (lạp xưởng, chả lụa, cà rốt, tôm) thái hạt lựu. Đậu, bắp, cà rốt luộc sơ.', 'Phi tỏi thơm, cho tôm và lạp xưởng vào xào chín, sau đó cho các nguyên liệu khác vào đảo đều.', 'Cho cơm nguội vào chảo, đảo tơi. Đập trứng vào, đảo thật nhanh tay để trứng bám đều vào hạt cơm.', 'Nêm nếm gia vị (nước tương, hạt nêm), thêm hành lá.', 'Rang ở lửa lớn đến khi hạt cơm săn lại và nhảy lên.'],
    durationInMinutes: 30,
    category: RecipeCategory.food,
  ),
  Recipe(
    id: 'r8',
    name: 'Bò Bít Tết (Beefsteak)',
    imageUrl: 'image/BeefSteak.jpg',
    ingredients: ['Thịt thăn bò (200g)', 'Khoai tây (2 củ)', 'Trứng gà (1 quả)', 'Bơ lạt, tỏi', 'Hương thảo (Rosemary)', 'Muối, tiêu'],
    steps: ['Rửa sạch thăn bò, thấm khô. Ướp với muối, tiêu và dầu ô liu.', 'Làm khoai tây chiên.', 'Làm nóng chảo gang. Cho bơ, tỏi đập dập và hương thảo vào.', 'Cho thăn bò vào áp chảo, mỗi mặt 2-3 phút (cho tái vừa - medium rare). Liên tục rưới bơ tỏi lên mặt thịt.', 'Làm trứng ốp la.', 'Dọn bít tết ra đĩa nóng, ăn kèm khoai tây và trứng ốp la.'],
    durationInMinutes: 20,
    category: RecipeCategory.food,
  ),
  Recipe(
    id: 'r9',
    name: 'Pizza Margherita',
    imageUrl: 'image/Pizza.jpg',
    ingredients: ['Đế pizza (1 cái)', 'Sốt cà chua (50ml)', 'Phô mai Mozzarella (100g)', 'Cà chua bi (vài quả)', 'Lá húng quế tươi (Basil)'],
    steps: ['Phết đều sốt cà chua lên đế pizza.', 'Rắc phô mai Mozzarella đã bào sợi.', 'Xếp cà chua bi cắt đôi và lá húng quế lên trên.', 'Nướng ở nhiệt độ 220°C trong 10-15 phút, cho đến khi đế giòn và phô mai chảy vàng.', 'Rưới thêm chút dầu ô liu khi thưởng thức.'],
    durationInMinutes: 20,
    category: RecipeCategory.food,
  ),
  Recipe(
    id: 'r10',
    name: 'Chả giò (Nem rán)',
    imageUrl: 'image/Nemran.jpg',
    ingredients: ['Thịt nạc vai xay (300g)', 'Tôm (100g)', 'Miến dong, mộc nhĩ, nấm hương', 'Cà rốt, su hào (hoặc giá đỗ)', 'Trứng (2 quả)', 'Vỏ bánh đa nem', 'Nước mắm chấm'],
    steps: ['Ngâm miến, mộc nhĩ, nấm hương cho mềm rồi băm nhỏ.', 'Bào sợi cà rốt, su hào. Tôm băm nhỏ.', 'Trộn tất cả nguyên liệu (trừ vỏ bánh đa nem) với thịt xay và trứng. Nêm gia vị vừa ăn.', 'Trải vỏ bánh đa nem, cho nhân vào và cuộn chặt tay.', 'Chiên ngập dầu lần 1 ở lửa vừa cho nem chín.', 'Chiên lần 2 ở lửa lớn hơn ngay trước khi ăn để nem giòn rụm.'],
    durationInMinutes: 60,
    category: RecipeCategory.food,
  ),
  Recipe(
    id: 'r11',
    name: 'Bánh Xèo',
    imageUrl: 'image/BanhXeo.jpg',
    ingredients: ['Bột bánh xèo (gói pha sẵn) (250g)', 'Nước cốt dừa (100ml)', 'Bia (hoặc nước soda) (50ml)', 'Bột nghệ', 'Thịt ba rọi (200g)', 'Tôm (200g)', 'Giá đỗ, hành lá', 'Rau sống, nước mắm chấm'],
    steps: ['Pha bột bánh xèo với nước cốt dừa, bia, bột nghệ và hành lá thái nhỏ. Để bột nghỉ 30 phút.', 'Thịt ba rọi luộc sơ, thái mỏng. Tôm làm sạch.', 'Làm nóng chảo, cho chút dầu. Cho thịt và tôm vào xào săn.', 'Đổ một vá bột vào chảo, tráng thật mỏng. Thêm giá đỗ.', 'Đậy vung khoảng 2 phút cho bánh chín và giá chín.', 'Mở vung, chiên thêm cho đến khi vỏ bánh giòn. Gập đôi bánh lại.', 'Ăn kèm rau sống và nước mắm chua ngọt.'],
    durationInMinutes: 45,
    category: RecipeCategory.food,
  ),
  
  Recipe(
    id: 'r13',
    name: 'Canh chua cá lóc',
    imageUrl: 'image/CanhChuaCaLoc.jpg',
    ingredients: ['Cá lóc (1 con vừa)', 'Dọc mùng (bạc hà)', 'Đậu bắp, cà chua, giá đỗ', 'Thơm (dứa)', 'Me vắt', 'Ngò om, quế, ớt'],
    steps: ['Cá lóc làm sạch, cắt khoanh, ướp gia vị.', 'Lấy nước cốt me.', 'Phi tỏi thơm, cho cà chua và thơm vào xào sơ.', 'Đổ nước vào nấu sôi, cho nước cốt me vào.', 'Nước sôi, cho cá lóc vào nấu chín.', 'Cho đậu bắp, dọc mùng vào nấu thêm 3 phút.', 'Cuối cùng cho giá đỗ. Nêm nếm lại cho vừa vị chua-mặn-ngọt.', 'Tắt bếp, cho ngò om, quế cắt nhỏ và ớt.'],
    durationInMinutes: 40,
    category: RecipeCategory.food,
  ),
  Recipe(
    id: 'r14',
    name: 'Bò kho',
    imageUrl: 'image/BoKho.jpg',
    ingredients: ['Thịt nạm bò (500g)', 'Cà rốt (2 củ)', 'Sả (3 cây)', 'Gừng, tỏi, hành tím', 'Bột gia vị bò kho (1 gói)', 'Rượu vang đỏ (50ml) (tùy chọn)', 'Hoa hồi, quế'],
    steps: ['Thịt bò cắt vuông, ướp với gừng, tỏi, hành tím băm, gói gia vị bò kho, chút đường, muối, tiêu trong 30 phút.', 'Phi thơm sả, tỏi. Cho thịt bò vào xào săn.', 'Thêm rượu vang đỏ (nếu có), đảo đều.', 'Đổ nước ngập mặt thịt, thêm hoa hồi, quế. Hầm ở lửa nhỏ 1.5 - 2 giờ cho thịt mềm.', 'Cà rốt cắt miếng, cho vào hầm thêm 20 phút.', 'Nêm nếm lại. Ăn kèm bánh mì hoặc hủ tiếu.'],
    durationInMinutes: 150,
    category: RecipeCategory.food,
  ),
  Recipe(
    id: 'r15',
    name: 'Miến xào cua',
    imageUrl: 'image/Mienxaocua.jpg',
    ingredients: ['Miến dong (200g)', 'Thịt cua (100g)', 'Tôm (100g)', 'Mộc nhĩ, nấm hương', 'Cà rốt, hành tây, giá đỗ', 'Trứng gà (1 quả)', 'Hành lá, ngò'],
    steps: ['Ngâm miến cho mềm, cắt khúc, trụng sơ nước sôi rồi xả nước lạnh, trộn với 1 muỗng dầu ăn cho tơi.', 'Ngâm mộc nhĩ, nấm hương cho mềm, thái sợi. Cà rốt, hành tây thái sợi.', 'Tôm bóc vỏ. Phi tỏi thơm, xào chín tôm và thịt cua, nêm gia vị.', 'Xào rau củ (cà rốt, hành tây, nấm) cho chín tới.', 'Cho miến vào chảo, đảo đều. Đập trứng vào, đảo nhanh tay cho trứng bám vào miến.', 'Cho tôm, cua, giá đỗ, hành lá vào đảo đều. Nêm lại gia vị và rắc tiêu.'],
    durationInMinutes: 40,
    category: RecipeCategory.food,
  ),
  Recipe(
    id: 'r16',
    name: 'Trà tắc',
    imageUrl: 'image/TraTac.jpg',
    ingredients: ['Trà đen (hoặc trà lài) (2 gói)', 'Tắc (quất) (10 quả)', 'Đường (100g)', 'Đá viên'],
    steps: ['Hãm 2 gói trà với 200ml nước sôi. Để nguội.', 'Nấu nước đường: 100g đường với 50ml nước cho tan.', 'Vắt lấy nước cốt 8 quả tắc. 2 quả còn lại cắt lát mỏng.', 'Pha trà: Cho nước trà, nước đường, nước cốt tắc vào bình, lắc đều.', 'Cho đá vào ly, rót trà, thêm vài lát tắc lên trên.'],
    durationInMinutes: 10,
    category: RecipeCategory.drink,
  ),
  Recipe(
    id: 'r17',
    name: 'Cà phê Cốt dừa',
    imageUrl: 'image/CaPheCotDua.jpg',
    ingredients: ['Cà phê phin (pha đậm đặc) (50ml)', 'Nước cốt dừa (loại đặc) (80ml)', 'Sữa đặc (60ml)', 'Đá xay (1 ly)'],
    steps: ['Pha một phin cà phê đậm đặc và để nguội.', 'Cho nước cốt dừa, sữa đặc và đá vào máy xay sinh tố.', 'Xay hỗn hợp ở tốc độ cao cho đến khi mịn như tuyết (khoảng 1-2 phút).', 'Đổ hỗn hợp cốt dừa ra ly.', 'Rót từ từ cà phê đã pha nguội lên trên để tạo phân tầng.'],
    durationInMinutes: 15,
    category: RecipeCategory.drink,
  ),
  Recipe(
    id: 'r18',
    name: 'Nước ép Cam',
    imageUrl: 'image/NuocCam.jpg',
    ingredients: ['Cam sành (3-4 quả)', 'Đường (tùy chọn)', 'Đá viên'],
    steps: ['Bổ đôi quả cam.', 'Dùng dụng cụ vắt cam để vắt lấy nước.', 'Lọc qua rây để loại bỏ hạt và tép cam to (nếu không thích).', 'Thêm đường nếu cam chua, khuấy tan.', 'Cho đá viên vào ly và rót nước cam vào thưởng thức.'],
    durationInMinutes: 5,
    category: RecipeCategory.drink,
  ),
  Recipe(
    id: 'r19',
    name: 'Sinh tố Xoài',
    imageUrl: 'image/SinhToXoai.jpg',
    ingredients: ['Xoài chín (1 quả)', 'Sữa tươi (100ml)', 'Sữa đặc (2 muỗng)', 'Đá viên (1 ly)'],
    steps: ['Xoài gọt vỏ, cắt miếng nhỏ.', 'Cho xoài, sữa tươi, sữa đặc và đá viên vào máy xay sinh tố.', 'Xay ở tốc độ cao cho đến khi hỗn hợp mịn.', 'Rót ra ly và thưởng thức.'],
    durationInMinutes: 10,
    category: RecipeCategory.drink,
  ),
  Recipe(
    id: 'r20',
    name: 'Trà sữa Trân châu',
    imageUrl: 'image/Trasuatranchau.jpg',
    ingredients: ['Trà đen (2 gói)', 'Sữa đặc (50ml)', 'Bột năng (100g)', 'Bột ca cao (10g)', 'Đường đen (50g)', 'Đá viên'],
    steps: ['Làm trân châu: Trộn bột năng, bột ca cao. Đổ nước sôi từ từ vào nhào bột. Vo thành viên nhỏ. Luộc trân châu 15 phút, tắt bếp ủ 15 phút. Vớt ra ngâm nước đá, rồi trộn với đường đen.', 'Pha trà: Hãm trà với 200ml nước sôi. Lọc bỏ bã.', 'Pha trà sữa: Cho sữa đặc vào trà nóng, khuấy tan.', 'Cho trân châu vào ly, thêm đá, rót trà sữa vào và thưởng thức.'],
    durationInMinutes: 60,
    category: RecipeCategory.drink,
  ),
];