import 'package:flutter/material.dart';
import '../l10n/app_localizations.dart';

class LocalizationHelper {
  static AppLocalizations loc(BuildContext context) =>
      AppLocalizations.of(context)!;

  static String getText(BuildContext context, String key) {
    final l = loc(context);
    switch (key) {
      case 'r1_name':
        return l.r1_name;
      case 'r1_ing_1':
        return l.r1_ing_1;
      case 'r1_ing_2':
        return l.r1_ing_2;
      case 'r1_ing_3':
        return l.r1_ing_3;
      case 'r1_ing_4':
        return l.r1_ing_4;
      case 'r1_ing_5':
        return l.r1_ing_5;
      case 'r1_step_1':
        return l.r1_step_1;
      case 'r1_step_2':
        return l.r1_step_2;
      case 'r1_step_3':
        return l.r1_step_3;
      case 'r1_step_4':
        return l.r1_step_4;
      case 'r1_step_5':
        return l.r1_step_5;
      case 'r1_step_6':
        return l.r1_step_6;
      case 'r2_name':
        return l.r2_name;
      case 'r2_ing_1':
        return l.r2_ing_1;
      case 'r2_ing_2':
        return l.r2_ing_2;
      case 'r2_ing_3':
        return l.r2_ing_3;
      case 'r2_ing_4':
        return l.r2_ing_4;
      case 'r2_ing_5':
        return l.r2_ing_5;
      case 'r2_ing_6':
        return l.r2_ing_6;
      case 'r2_ing_7':
        return l.r2_ing_7;
      case 'r2_step_1':
        return l.r2_step_1;
      case 'r2_step_2':
        return l.r2_step_2;
      case 'r2_step_3':
        return l.r2_step_3;
      case 'r2_step_4':
        return l.r2_step_4;
      case 'r2_step_5':
        return l.r2_step_5;
      case 'r2_step_6':
        return l.r2_step_6;
      case 'r3_name':
        return l.r3_name;
      case 'r3_ing_1':
        return l.r3_ing_1;
      case 'r3_ing_2':
        return l.r3_ing_2;
      case 'r3_ing_3':
        return l.r3_ing_3;
      case 'r3_ing_4':
        return l.r3_ing_4;
      case 'r3_ing_5':
        return l.r3_ing_5;
      case 'r3_step_1':
        return l.r3_step_1;
      case 'r3_step_2':
        return l.r3_step_2;
      case 'r3_step_3':
        return l.r3_step_3;
      case 'r3_step_4':
        return l.r3_step_4;
      case 'r3_step_5':
        return l.r3_step_5;
      case 'r4_name':
        return l.r4_name;
      case 'r4_ing_1':
        return l.r4_ing_1;
      case 'r4_ing_2':
        return l.r4_ing_2;
      case 'r4_ing_3':
        return l.r4_ing_3;
      case 'r4_ing_4':
        return l.r4_ing_4;
      case 'r4_ing_5':
        return l.r4_ing_5;
      case 'r4_ing_6':
        return l.r4_ing_6;
      case 'r4_step_1':
        return l.r4_step_1;
      case 'r4_step_2':
        return l.r4_step_2;
      case 'r4_step_3':
        return l.r4_step_3;
      case 'r4_step_4':
        return l.r4_step_4;
      case 'r4_step_5':
        return l.r4_step_5;
      case 'r4_step_6':
        return l.r4_step_6;
      case 'r5_name':
        return l.r5_name;
      case 'r5_ing_1':
        return l.r5_ing_1;
      case 'r5_ing_2':
        return l.r5_ing_2;
      case 'r5_ing_3':
        return l.r5_ing_3;
      case 'r5_ing_4':
        return l.r5_ing_4;
      case 'r5_ing_5':
        return l.r5_ing_5;
      case 'r5_step_1':
        return l.r5_step_1;
      case 'r5_step_2':
        return l.r5_step_2;
      case 'r5_step_3':
        return l.r5_step_3;
      case 'r5_step_4':
        return l.r5_step_4;
      case 'r5_step_5':
        return l.r5_step_5;
      case 'r5_step_6':
        return l.r5_step_6;
      case 'r7_name':
        return l.r7_name;
      case 'r7_ing_1':
        return l.r7_ing_1;
      case 'r7_ing_2':
        return l.r7_ing_2;
      case 'r7_ing_3':
        return l.r7_ing_3;
      case 'r7_ing_4':
        return l.r7_ing_4;
      case 'r7_ing_5':
        return l.r7_ing_5;
      case 'r7_ing_6':
        return l.r7_ing_6;
      case 'r7_step_1':
        return l.r7_step_1;
      case 'r7_step_2':
        return l.r7_step_2;
      case 'r7_step_3':
        return l.r7_step_3;
      case 'r7_step_4':
        return l.r7_step_4;
      case 'r7_step_5':
        return l.r7_step_5;
      case 'r8_name':
        return l.r8_name;
      case 'r8_ing_1':
        return l.r8_ing_1;
      case 'r8_ing_2':
        return l.r8_ing_2;
      case 'r8_ing_3':
        return l.r8_ing_3;
      case 'r8_ing_4':
        return l.r8_ing_4;
      case 'r8_ing_5':
        return l.r8_ing_5;
      case 'r8_ing_6':
        return l.r8_ing_6;
      case 'r8_step_1':
        return l.r8_step_1;
      case 'r8_step_2':
        return l.r8_step_2;
      case 'r8_step_3':
        return l.r8_step_3;
      case 'r8_step_4':
        return l.r8_step_4;
      case 'r8_step_5':
        return l.r8_step_5;
      case 'r8_step_6':
        return l.r8_step_6;
      case 'r9_name':
        return l.r9_name;
      case 'r9_ing_1':
        return l.r9_ing_1;
      case 'r9_ing_2':
        return l.r9_ing_2;
      case 'r9_ing_3':
        return l.r9_ing_3;
      case 'r9_ing_4':
        return l.r9_ing_4;
      case 'r9_ing_5':
        return l.r9_ing_5;
      case 'r9_step_1':
        return l.r9_step_1;
      case 'r9_step_2':
        return l.r9_step_2;
      case 'r9_step_3':
        return l.r9_step_3;
      case 'r9_step_4':
        return l.r9_step_4;
      case 'r9_step_5':
        return l.r9_step_5;
      case 'r10_name':
        return l.r10_name;
      case 'r10_ing_1':
        return l.r10_ing_1;
      case 'r10_ing_2':
        return l.r10_ing_2;
      case 'r10_ing_3':
        return l.r10_ing_3;
      case 'r10_ing_4':
        return l.r10_ing_4;
      case 'r10_ing_5':
        return l.r10_ing_5;
      case 'r10_ing_6':
        return l.r10_ing_6;
      case 'r10_ing_7':
        return l.r10_ing_7;
      case 'r10_step_1':
        return l.r10_step_1;
      case 'r10_step_2':
        return l.r10_step_2;
      case 'r10_step_3':
        return l.r10_step_3;
      case 'r10_step_4':
        return l.r10_step_4;
      case 'r10_step_5':
        return l.r10_step_5;
      case 'r10_step_6':
        return l.r10_step_6;
      case 'r11_name':
        return l.r11_name;
      case 'r11_ing_1':
        return l.r11_ing_1;
      case 'r11_ing_2':
        return l.r11_ing_2;
      case 'r11_ing_3':
        return l.r11_ing_3;
      case 'r11_ing_4':
        return l.r11_ing_4;
      case 'r11_ing_5':
        return l.r11_ing_5;
      case 'r11_ing_6':
        return l.r11_ing_6;
      case 'r11_ing_7':
        return l.r11_ing_7;
      case 'r11_ing_8':
        return l.r11_ing_8;
      case 'r11_step_1':
        return l.r11_step_1;
      case 'r11_step_2':
        return l.r11_step_2;
      case 'r11_step_3':
        return l.r11_step_3;
      case 'r11_step_4':
        return l.r11_step_4;
      case 'r11_step_5':
        return l.r11_step_5;
      case 'r11_step_6':
        return l.r11_step_6;
      case 'r11_step_7':
        return l.r11_step_7;
      case 'r13_name':
        return l.r13_name;
      case 'r13_ing_1':
        return l.r13_ing_1;
      case 'r13_ing_2':
        return l.r13_ing_2;
      case 'r13_ing_3':
        return l.r13_ing_3;
      case 'r13_ing_4':
        return l.r13_ing_4;
      case 'r13_ing_5':
        return l.r13_ing_5;
      case 'r13_ing_6':
        return l.r13_ing_6;
      case 'r13_step_1':
        return l.r13_step_1;
      case 'r13_step_2':
        return l.r13_step_2;
      case 'r13_step_3':
        return l.r13_step_3;
      case 'r13_step_4':
        return l.r13_step_4;
      case 'r13_step_5':
        return l.r13_step_5;
      case 'r13_step_6':
        return l.r13_step_6;
      case 'r13_step_7':
        return l.r13_step_7;
      case 'r13_step_8':
        return l.r13_step_8;
      case 'r14_name':
        return l.r14_name;
      case 'r14_ing_1':
        return l.r14_ing_1;
      case 'r14_ing_2':
        return l.r14_ing_2;
      case 'r14_ing_3':
        return l.r14_ing_3;
      case 'r14_ing_4':
        return l.r14_ing_4;
      case 'r14_ing_5':
        return l.r14_ing_5;
      case 'r14_ing_6':
        return l.r14_ing_6;
      case 'r14_ing_7':
        return l.r14_ing_7;
      case 'r14_step_1':
        return l.r14_step_1;
      case 'r14_step_2':
        return l.r14_step_2;
      case 'r14_step_3':
        return l.r14_step_3;
      case 'r14_step_4':
        return l.r14_step_4;
      case 'r14_step_5':
        return l.r14_step_5;
      case 'r14_step_6':
        return l.r14_step_6;
      case 'r15_name':
        return l.r15_name;
      case 'r15_ing_1':
        return l.r15_ing_1;
      case 'r15_ing_2':
        return l.r15_ing_2;
      case 'r15_ing_3':
        return l.r15_ing_3;
      case 'r15_ing_4':
        return l.r15_ing_4;
      case 'r15_ing_5':
        return l.r15_ing_5;
      case 'r15_ing_6':
        return l.r15_ing_6;
      case 'r15_ing_7':
        return l.r15_ing_7;
      case 'r15_step_1':
        return l.r15_step_1;
      case 'r15_step_2':
        return l.r15_step_2;
      case 'r15_step_3':
        return l.r15_step_3;
      case 'r15_step_4':
        return l.r15_step_4;
      case 'r15_step_5':
        return l.r15_step_5;
      case 'r15_step_6':
        return l.r15_step_6;
      case 'r16_name':
        return l.r16_name;
      case 'r16_ing_1':
        return l.r16_ing_1;
      case 'r16_ing_2':
        return l.r16_ing_2;
      case 'r16_ing_3':
        return l.r16_ing_3;
      case 'r16_ing_4':
        return l.r16_ing_4;
      case 'r16_step_1':
        return l.r16_step_1;
      case 'r16_step_2':
        return l.r16_step_2;
      case 'r16_step_3':
        return l.r16_step_3;
      case 'r16_step_4':
        return l.r16_step_4;
      case 'r16_step_5':
        return l.r16_step_5;
      case 'r17_name':
        return l.r17_name;
      case 'r17_ing_1':
        return l.r17_ing_1;
      case 'r17_ing_2':
        return l.r17_ing_2;
      case 'r17_ing_3':
        return l.r17_ing_3;
      case 'r17_ing_4':
        return l.r17_ing_4;
      case 'r17_step_1':
        return l.r17_step_1;
      case 'r17_step_2':
        return l.r17_step_2;
      case 'r17_step_3':
        return l.r17_step_3;
      case 'r17_step_4':
        return l.r17_step_4;
      case 'r17_step_5':
        return l.r17_step_5;
      case 'r18_name':
        return l.r18_name;
      case 'r18_ing_1':
        return l.r18_ing_1;
      case 'r18_ing_2':
        return l.r18_ing_2;
      case 'r18_ing_3':
        return l.r18_ing_3;
      case 'r18_step_1':
        return l.r18_step_1;
      case 'r18_step_2':
        return l.r18_step_2;
      case 'r18_step_3':
        return l.r18_step_3;
      case 'r18_step_4':
        return l.r18_step_4;
      case 'r18_step_5':
        return l.r18_step_5;
      case 'r19_name':
        return l.r19_name;
      case 'r19_ing_1':
        return l.r19_ing_1;
      case 'r19_ing_2':
        return l.r19_ing_2;
      case 'r19_ing_3':
        return l.r19_ing_3;
      case 'r19_ing_4':
        return l.r19_ing_4;
      case 'r19_step_1':
        return l.r19_step_1;
      case 'r19_step_2':
        return l.r19_step_2;
      case 'r19_step_3':
        return l.r19_step_3;
      case 'r19_step_4':
        return l.r19_step_4;
      case 'r20_name':
        return l.r20_name;
      case 'r20_ing_1':
        return l.r20_ing_1;
      case 'r20_ing_2':
        return l.r20_ing_2;
      case 'r20_ing_3':
        return l.r20_ing_3;
      case 'r20_ing_4':
        return l.r20_ing_4;
      case 'r20_ing_5':
        return l.r20_ing_5;
      case 'r20_ing_6':
        return l.r20_ing_6;
      case 'r20_step_1':
        return l.r20_step_1;
      case 'r20_step_2':
        return l.r20_step_2;
      case 'r20_step_3':
        return l.r20_step_3;
      case 'r20_step_4':
        return l.r20_step_4;
      default:
        return key;
    }
  }

  static List<String> getList(BuildContext context, List<String> keys) {
    return keys.map((key) => getText(context, key)).toList();
  }
}
